@startuml
'https://plantuml.com/class-diagram

class Customer{
name:string
password:string
role:string[]
}
class Admin{
name:string
password:string
role:string[]
}
class Price{
value:double
currency:string
}
class ProductInfo{
quantity:int
measure:string
}
class Product{
name:string
quantity:int
}
class Pizza{
name:string
description:string
}
class SupplyItem{
date:Date
}
class Supplier{
name:string
phoneNumber:string
}
Product "n"--o "1" Pizza
ProductInfo --o Product
Price --o Product
SupplyItem --o Supplier
Product "n"--o "1" SupplyItem
@enduml